ECommerceWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from home import views


urlpatterns = [
    path('', views.index ,name='index'),
    path('signup', views.signup ,name='signup'),
    path('login', views.loginPage ,name='loginPage'),
    path('LogoutPage', views.LogoutPage ,name='LogutPage'),
    path('homepage', views.home ,name='homepage'),
    path('reset_password', views.PasswordReset ,name='PasswordReset'),
    path('contactpage',views.contactPage, name = 'contact'),
    path('account',views.accountDetail, name='account'),
    path('search/',views.searchproduct, name='search'),
    path('payment/',views.stripePayment, name='payment'),

    # For the password Reset functionality:
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name='reset_password'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name='password_reset_done'),

    path('reset/<uid64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_complete'),

    # From the django-Shopping-Cart feture:
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart-detail/',views.cart_detail,name='cart_detail'),

    #Checkout Page:
    path('checkout/',views.CheckoutPage, name='checkout'),
    path('order/',views.Your_Order, name='order'),
    path('product/',views.productpage, name='product'),
    path('product/<str:id>',views.productDetail, name='productDetail'),
    

]   

home/models.py
from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

import datetime

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)


    def __str__(self):
        return self.name


class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class profession(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    Availability = (('In Stock' , 'In Stock'),('Out Of Stock' , 'Out Of Stock'))

    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=False, default='')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE,null=False, default='')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    Availability = models.CharField(choices=Availability, null = True, max_length=100)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.email


class Order(models.Model):
    image = models.ImageField(upload_to = 'ecommerce/order/image')
    product = models.CharField(max_length=50, default='')
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=5)
    total = models.CharField(max_length=100, default='')
    address = models.TextField()
    phone = models.CharField(max_length=10)
    pincode = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)
    
    def __str__(self):
        return self.product
    
class userProfile(models.Model):
    Profile_image = models.ImageField(upload_to='ecommerce/accimg', blank=True, null=True)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
class Details(models.Model):
    image = models.ImageField(upload_to='ecommerce/pimg')
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    
    def __str__(self):
        return self.user.username

home/views.py
from django.shortcuts import render, redirect, HttpResponse
from home.models import Category, Product, Contact_us, Order, Brand, userProfile, profession, Details
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth.decorators import login_required
from cart.cart import Cart

# Create your views here.
def index(request):
    category = Category.objects.all()
    brand = Brand.objects.all()
    product_tshirts = Product.objects.filter(sub_category__name = "T-Shirts")
    product_shirts = Product.objects.filter(sub_category__name = "Shirts")
    product_trousers = Product.objects.filter(sub_category__name = "Trousers", price__lt=3300)
    product_kids = Product.objects.filter(sub_category__name = "PartyWear")
    recommended = Product.objects.filter(price__lte=1500)


    categoryID = request.GET.get('category')
    brandID = request.GET.get('brand')
    if categoryID:
        product = Product.objects.filter(sub_category = categoryID).order_by('-id')
    elif brandID:
        product = Product.objects.filter(brand = brandID).order_by('-id')
    else:
        product = Product.objects.all()

    
    
    context = {
        'category':category,
        'product':product,
        'brand':brand,
        'product_tshirts':product_tshirts,
        'product_shirts':product_shirts,
        'product_trousers':product_trousers,
        'product_kids':product_kids,
        'recommended':recommended
    }

    return render(request,'index.html',context)



def signup(request):
    if request.method == 'POST':
        uname = request.POST.get("username")
        email = request.POST.get("email")
        pass1 = request.POST.get("password1")
        pass2 = request.POST.get("password2")

        if pass1 != pass2:
            return HttpResponse("Password and confirm Passwords are not same")
        
        else:
            my_user = User.objects.create_user(uname,email,pass1)
            my_user.save()
            return redirect('loginPage')
        
        # image = 
        # profile = userProfile(user=my_user, image = )

    return render(request,'signup.html')

def loginPage(request):
    if request.method == 'POST':
        uname = request.POST.get("username")
        pass1 = request.POST.get("pass")

        user = authenticate(request,username=uname,password=pass1)
        if user is not None:
            # loging in the user
            login(request,user)
            return redirect('homepage')
        else:
            return HttpResponse("Either Username or Password is Invalid:")

    return render(request,'login.html')


def LogoutPage(request):
    logout(request)
    return redirect('index')

# @login_required(login_url='index')

def home(request):
    category = Category.objects.all()
    brand = Brand.objects.all()
    product_tshirts = Product.objects.filter(sub_category__name = "T-Shirts")
    product_shirts = Product.objects.filter(sub_category__name = "Shirts")
    product_trousers = Product.objects.filter(sub_category__name = "Trousers", price__lt=3300)
    product_kids = Product.objects.filter(sub_category__name = "PartyWear")
    recommended = Product.objects.filter(price__lte=1500)


    categoryID = request.GET.get('category')
    brandID = request.GET.get('brand')
    if categoryID:
        product = Product.objects.filter(sub_category = categoryID).order_by('-id')
    elif brandID:
        product = Product.objects.filter(brand = brandID).order_by('-id')
    else:
        product = Product.objects.all()

    
    
    context = {
        'category':category,
        'product':product,
        'brand':brand,
        'product_tshirts':product_tshirts,
        'product_shirts':product_shirts,
        'product_trousers':product_trousers,
        'product_kids':product_kids,
        'recommended':recommended
    }

    return render(request,'home.html',context)



def PasswordReset(request):
    return render(request,'Password_Reset_Form.html')


# For the Cart based Details:
@login_required(login_url="/accounts/login/")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("homepage")


@login_required(login_url="/accounts/login/")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/accounts/login/")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/accounts/login/")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/accounts/login/")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/accounts/login/")
def cart_detail(request):
    return render(request, 'cart/cart_detail.html')


def contactPage(request):
    if request.method == "POST":
        contact = Contact_us(
            name = request.POST.get('name'),
            email = request.POST.get('email'),
            subject = request.POST.get('subject'),
            message = request.POST.get('message')
        )
        contact.save()

    return render(request,'contact.html')

def CheckoutPage(request):
    if request.method == "POST":
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        pincode = request.POST.get('pincode')
        cart = request.session.get('cart')
        uid = request.session.get('_auth_user_id')
        user = User.objects.get(pk = uid)

        for i in cart:
            a = int(cart[i]['price'])
            b = cart[i]['quantity']
            total = a*b
            order = Order(
                user = user,
                product = cart[i]['name'],
                price = cart[i]['price'],
                quantity = cart[i]['quantity'],
                image = cart[i]['image'],
                address = address,
                pincode = pincode,
                phone = phone,
                total = total
            )

            order.save()
        return redirect('homepage')

    return HttpResponse("This is our checkout Page see this:")

def Your_Order(request):
    uid = request.session.get('_auth_user_id')
    user = User.objects.get(pk = uid)

    order = Order.objects.filter(user = user)

    context = {
        "order": order
    }
    return render(request, 'order.html', context)

def productpage(request):
    category = Category.objects.all()
    brand = Brand.objects.all()

    categoryID = request.GET.get('category')
    brandID = request.GET.get('brand')
    if categoryID:
        product = Product.objects.filter(sub_category = categoryID).order_by('-id')

    elif brandID:
        product = Product.objects.filter(brand = brandID).order_by('-id')

    else:
        product = Product.objects.all()
    
    context = {
        'category':category,
        'product':product,
        'brand':brand
    }

    return render(request, 'product.html', context)

def productDetail(request, id):
    category = Category.objects.all()
    brand = Brand.objects.all()
    product = Product.objects.filter(id = id).first()
    product_tshirts = Product.objects.filter(sub_category__name = "T-Shirts")
    product_shirts = Product.objects.filter(sub_category__name = "Shirts")
    product_trousers = Product.objects.filter(sub_category__name = "Trousers", price__lt=3300)
    product_kids = Product.objects.filter(sub_category__name = "PartyWear")
    recommended = Product.objects.filter(price__lte=1500)
    
    context = {
        'category':category,
        'product':product,
        'brand':brand,
        'product_tshirts':product_tshirts,
        'product_shirts':product_shirts,
        'product_trousers':product_trousers,
        'product_kids':product_kids,
        'recommended':recommended
    }
    return render(request, 'product_detail.html',context)

def accountDetail(request):
    # Passing the user information to the Page:
    uid = request.session.get('_auth_user_id')
    user = User.objects.get(pk = uid)

    profile = Details.objects.filter(user = user)

    context ={
        'user':user,
        'profile':profile
    }
    
    return render(request, 'Account.html', context)


def searchproduct(request):
    query = request.GET['query']
    product = Product.objects.filter(name__icontains = query)

    context = {
        'product':product
    }
    return render(request, 'search.html', context)

def stripePayment(request):
    return render(request, 'payment.html')


# def get_context_data(sel, **kwargs):
#     context = super().get_context_data(**kwargs)
#     context['key'] = settings.STRIPE_PUBLISHABLE_KEY
#     return context

templates/Account.html
{% extends 'master2.html' %}
{% block body %}
  <div class='container' style='display: flex; flex-direction:row; justify-Content: space-between'>
    <div>
      {% for i in profile %}
          <img src="{{profile.image}}" alt="{{profile.user.username}}" width="200" height="200" style='border: 2px solid black; border-radius:100px'>
          <h4 style='text-align:center'>{{user.username}}</h4>
          <p style='text-align:center'>Customer</p>
          <p class="text-muted font-size-sm">Flat No.345/456 East Mumbai</p>
          <div style='display: flex; flex-direction:row; justify-Content: center'>
            <button class="btn btn-primary">EditProfile</button>
          </div>
      {% endfor %}
          <br>
    </div>  

    <div style='width:500px; margin-bottom:20px; border: 2px solid black; border-radius:10px; padding: 10px 10px'>
        <p><span style='font-size:25px'>Username:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><span style='font-size:25px'>{{user.username}}</span></p><hr>
        <p><span style='font-size:25px'>Email:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><span style='font-size:25px'>{{user.email}}</span></p><hr>
        <p><span style='font-size:25px'>First Name:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><span style='font-size:25px'>{{user.first_name}}</span></p><hr>
        <p><span style='font-size:25px'>Last Name:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><span style='font-size:25px'>{{user.last_name}}</span></p><hr>
    </div>

  </div>

  


{% endblock %}

templates/home.html
{% extends 'master2.html' %}

{% block body %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Big Dhamaal E-Shopper Season</h2>
									<p>Get huge Discounts within the ongoing Festive Season sale on E-Shopper.</p>
									<button type="button" class="btn btn-default get">All Time special Offers</button>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl1.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Real and Good Quality Fabric</h2>
									<p>You will get the Best Quality products shopping with E-Shopper. It will prove the best Choice for you: </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl2.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Special Offer For Women and Children</h2>
									<p>Get more offers on Women and children Stuff with exciting discounts and huge Variety specifically in this festive Season. </p>
									<button type="button" class="btn btn-default get">Hurry its Your Time Now</button>
								</div>
								<div class="col-sm-6">
									<img src="/static/images/home/girl3.jpg" class="girl img-responsive" alt="" />
									<img src="/static/images/home/pricing.png" class="pricing" alt="" />
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->


	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								{% for cat in category %}
									<div class="panel-heading">
										<h4 class="panel-title">
											<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
												<span class="badge pull-right"><i class="fa fa-plus"></i></span>
												{{cat.name}}
											</a>
										</h4>
									</div> 
									<div id="{{cat.id}}" class="panel-collapse collapse">
										<div class="panel-body">
											<ul>
												{% for i in cat.sub_category_set.all %}
													<li><a href="/homepage?category={{i.id}}">{{i.name}}</a></li>
												{% endfor %}
											</ul>
										</div>
									</div>
								{% endfor %}
							</div>
							
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Kids</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Fashion</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Households</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Interiors</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Clothing</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Bags</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Shoes</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
										<li><a href="/homepage?brand={{i.id}}"> <span class="pull-right">(10)</span>{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->
						
						{% comment %} <div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">₹ 0</b> <b class="pull-right">₹ 600</b>
							</div>
						</div><!--/price-range-->  {% endcomment %}
						
						<div class="shipping text-center"><!--shipping-->
							<img src="/static/images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->
					
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						{% for prod in product %}
							<div class="col-sm-3">
								<div class="product-image-wrapper">
									<div class="single-products">
											<div class="productinfo text-center">
												<img src="{{prod.image}}" alt="Reloading" style='height:200px; border: 1px solid black; border-radius: 20px' />
												<h2>₹{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
											<div class="product-overlay">
												<div class="overlay-content">
													<h2>₹{{prod.price}}</h2>
													<p>{{prod.name}}</p>
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
											</div>
									</div>
									<div class="choose">
										<ul class="nav nav-pills nav-justified">
											<li><a href="product/{{prod.id}}"><i class="fa fa-plus-square"></i>View More</a></li>
										</ul>
									</div>
								</div>
							</div>
						{% endfor %}
					</div><!--features_items-->
					
					<div class="category-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<li class="active"><a href="#tshirt" data-toggle="tab">T-Shirt</a></li>
								<li><a href="#blazers" data-toggle="tab">Shirts</a></li>
								<li><a href="#sunglass" data-toggle="tab">Trousers</a></li>
								<li><a href="#kids" data-toggle="tab">Kids</a></li>
							</ul>
						</div>
						
						<div class="tab-content">
							<div class="tab-pane fade active in" id="tshirt" >
								{% for prod in product_tshirts %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
													<h2>₹{{prod.price}}</h2>
													<p>{{prod.name}}</p>
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
							
							<div class="tab-pane fade" id="blazers" >
								{% for prod in product_shirts %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
													<h2>₹{{prod.price}}</h2>
													<p>{{prod.name}}</p>
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
							<div class="tab-pane fade" id="sunglass" >
								{% for prod in product_trousers %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
													<h2>₹{{prod.price}}</h2>
													<p>{{prod.name}}</p>
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
											</div>
										</div>
									</div>
								{% endfor %}
							</div>
							
							<div class="tab-pane fade" id="kids" >
								{% for prod in product_kids %}
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
													<h2>₹{{prod.price}}</h2>
													<p>{{prod.name}}</p>
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								{% endfor %}	
							</div>
						</div>
					</div><!--/category-tab-->
					
					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">
									{% for prod in recommended %}
										<div class="col-sm-3">
											<div class="product-image-wrapper">
												<div class="single-products">
													<div class="productinfo text-center">
														<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
														<h2>₹{{prod.price}}</h2>
														<p>{{prod.name}}</p>
														<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
													</div>
													
												</div>
											</div>
										</div>
									{% endfor %}
								</div>
								<div class="item">	
									{% for prod in recommended %}
										<div class="col-sm-3">
											<div class="product-image-wrapper">
												<div class="single-products">
													<div class="productinfo text-center">
														<img src="{{prod.image}}" alt="" style='height:200px; border: 1px solid black; border-radius: 20px' />
														<h2>₹{{prod.price}}</h2>
														<p>{{prod.name}}</p>
														<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
													</div>
													
												</div>
											</div>
										</div>
									{% endfor %}
								</div>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div><!--/recommended_items-->
					
				</div>
			</div>
		</div>
	</section>
		
{% endblock  %}

templates/login.html
{% extends 'master.html' %}

{% block body %}
<div class="container" style="margin-bottom:20px">
    <div class="col-sm-4 col-sm-offset-1" style="margin-left:380px">
        <div class="login-form"><!--login form-->
            <h1>Login Here</h1>
            <form method="post">
            {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" placeholder="Username" name="username" id="username">

                <label for="password1">Password</label>
                <input type="password" placeholder="Password" id="password1" name="pass">
                
                <button type="submit" class="btn btn-default" style="width:355px">Login</button>
                <span>
                    <a href="{% url 'signup' %}" >Create an account</a>
                    <a href="{% url 'reset_password' %}" style="float:right">Forgot Password</a>
                </span>
            </form>
        </div><!--/login form-->
    </div>
</div>
{% endblock %}

templates/payment.html
{% extends 'master2.html' %}

{% block body %}
<h1> Pyment Processing Through STRIPE:</h1>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key = "{{key}}"
    data-description="Payment Gateway"
    data-amount="500"
    data-collection="auto">
</script>
<br>
{% endblock %}